import logging
import os


class SmdaConfig:
    # keep this in sync with smda.__version__
    VERSION = "4.2.0"
    ESCAPER_DOWNWARD_COMPATIBILITY = "1.13.16"
    CONFIG_FILE_PATH = str(os.path.abspath(__file__))
    PROJECT_ROOT = str(os.path.abspath(os.sep.join([CONFIG_FILE_PATH, "..", "..", ".."])))

    ### An (optional) WinAPI database as generated by ApiScout (https://github.com/danielplohmann/apiscout)
    API_COLLECTION_FILES = {}
    ### global logging-config setup
    # Only do basicConfig if no handlers have been configured
    LOG_PATH = "./"
    LOG_LEVEL = logging.INFO
    LOG_FORMAT = "%(asctime)-15s: %(name)-32s - %(message)s"

    ### SMDA disassembler config
    # maximum time in seconds for disassembly to complete
    TIMEOUT = 300
    # maximum number of bytes to allocate while loading
    MAX_IMAGE_SIZE = 100 * 1024 * 1024
    # store raw binary buffer in SmdaReport to enable carving data from refs
    STORE_BUFFER = False
    # extract strings during disassembly
    WITH_STRINGS = False
    # the queue to use for candidate management
    CANDIDATE_QUEUE = "PriorityQueue"  # choose from: ["BracketQueue", "PriorityQueue"]
    # improve disassembly by resolving references through data flows
    USE_ALIGNMENT = True
    USE_SYMBOLS_AS_CANDIDATES = True
    RESOLVE_REGISTER_CALLS = True
    # limit this to avoid blowing up analysis time for weird samples
    MAX_INDIRECT_CALLS_PER_BASIC_BLOCK = 50
    # Intel interior-gap recovery budgets (0 == auto-scale from mapped image size)
    GAP_RECOVERY_MAX_PASSES = 2
    GAP_RECOVERY_MAX_EXTRA_ANALYSES = 0
    GAP_RECOVERY_EXTRA_ANALYSES_PER_MB = 200
    GAP_RECOVERY_EXTRA_ANALYSES_FLOOR = 500
    GAP_RECOVERY_MAX_EXTRA_ANALYSES_CAP = 8000
    GAP_INTERIOR_HOLE_MAX_ROUNDS = 2
    GAP_INTERIOR_HOLE_MAX_ATTEMPTS_PER_PASS = 1024
    GAP_INTERIOR_HOLE_MAX_SCAN_BYTES = 4096
    GAP_LARGE_UNMAPPED_MIN_BYTES = 512
    GAP_SMALL_UNMAPPED_MIN_BYTES = 64
    GAP_SMALL_UNMAPPED_ONLY_WHEN_FUNCTIONS_BELOW = 3000
    GAP_UNMAPPED_CODE_REF_TARGET_LIMIT = 512
    # backstops against memory usage explosion during candidate identification on pathological/junk samples
    # maximum number of function candidates to track; 0 == unlimited. Normal binaries have orders of magnitude fewer.
    MAX_FUNCTION_CANDIDATES = 200000
    # maximum number of inbound call references tracked per candidate; 0 == unlimited. Bounds set growth and rescoring.
    MAX_CALL_REFS_PER_CANDIDATE = 2000
    HIGH_ACCURACY = True
    RESOLVE_TAILCALLS = True
    # optional metadata generation options
    CALCULATE_SCC = True
    CALCULATE_NESTING = True
    CALCULATE_HASHING = True
    # confidence score to use for filtering functions before including them in the output
    CONFIDENCE_THRESHOLD = 0.0

    def __init__(self):
        self._disableLiefLogging()

    def _disableLiefLogging(self):
        # disable excessive logging from LIEF
        try:
            import lief

            lief.logging.disable()
        except ImportError:
            pass
